### ISSUE TITLE
Extension is way too big

### ISSUE THREAD

**Issue by inosik** [a-wart/ariake-dark#1]
The extension contains ~30 MB of Node packages. Please add a `.vscodeignore` file to only include files which are needed.

**Comment by a-wart** [comment]
@inosik thanks for noticing that. 
done and re-published now:)
https://github.com/a-wart/ariake-dark/commit/a6d762885774b6041d18a53e48a3eb31caa95d45

**Comment by inosik** [comment]
Yeah, the first install took like forever :smile: 

Thanks!

**Comment by inosik** [comment]
Version 0.0.3 still has all the Node packages :confused:

All the other `.vscodeignore` files I've seen [add `**` to the directory names](https://github.com/OmniSharp/omnisharp-vscode/blob/master/.vscodeignore). Maybe you should do the same?

**Comment by a-wart** [comment]
@inosik oh, I see. but it's strange to make .[something]ignore to behave not like `.gitignore` does
 — and that confused me.)
I've republished theme with /** pattern in .vscodeignore anyway in v0.0.4, thank you
