### ISSUE TITLE
Comments in diff are unreadable

### ISSUE THREAD

**Issue by TimonVS** [a-wart/ariake-dark#3]
![image](https://user-images.githubusercontent.com/876666/53876315-d17b2200-4006-11e9-9a23-3e7c41e1145c.png)

The colors can be changed with `diffEditor.insertedTextBackground`, `diffEditor.removedTextBackground` and possibly we can also use `diffEditor.insertedTextBorder` and `diffEditor.removedTextBorder`. I just don't know which colors to use :)

**Comment by TimonVS** [comment]
Changed my settings to this:

```
"workbench.colorCustomizations": {
    "[Ariake Dark]": {
      "editor.selectionBackground": "#ffffff21",
      "diffEditor.insertedTextBackground": "#43D08A10",
      "diffEditor.removedTextBackground": "#E052521A"
    }
  },
```

This is the result:

![image](https://user-images.githubusercontent.com/876666/53877086-895cff00-4008-11e9-8338-cd81e2e2af8f.png)

I extracted the values from the Atom theme: https://github.com/pathtrk/ariake-dark-syntax/blob/master/styles/syntax-variables.less. Does this seem alright? If so I'd happily make a PR.

**Comment by a-wart** [comment]
@TimonVS looks much better! sure, just submit the PR:)
